version: "3"

services:
    qbittorrent:
        container_name: qbittorrent
        image: linuxserver/qbittorrent:latest
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - WEBUI_PORT=8080
        volumes:
            - ./config:/config
            - ./downloads:/downloads
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped
