version: "3"

services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        environment:
            TZ: "Europe/Berline"
        volumes:
            - /docker/appdata/pihole/pihole:/etc/pihole
            - /docker/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 81:80/tcp
        restart: unless-stopped
