version: "3"

services:
    heimdall:
        container_name: heimdall
        image: linuxserver/heimdall:latest
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /docker/appdata/heimdall:/config
        ports:
            - 80:80
            - 443:433
        restart: unless-stopped
