version: "3"

services:
    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /docker/appdata/lidarr:/config
            - /data:/data
        ports:
            - 8686:8686
        restart: unless-stopped
