version: "3"

services:
    lidarr:
        image: lscr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./config:/config
            - ./music:/music
            - ./downloads:/downloads
        ports:
            - 8686:8686
        restart: unless-stopped
